### 
GET http://localhost:8080/productList

###
GET http://localhost:8080/productInfo?id=2

###
POST http://localhost:8080/productInfo
Content-Type: application/json

{
    "category": "Spreads",
    "product": "Premium Sauce",
    "inStock": "No",
    "price": "$13.99"
}